version: '3.4'

services:
  moviesapi:
    container_name: webapibackend
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - moviesdb
  
  moviesdb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: webapidb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "R00TRooT"
      MSSQL_PID: Express
    ports:
        - "1433:1433"
